
fp_openid_security:
    resource: "@FpOpenIdBundle/Resources/config/routing/security.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

wg_openiduser_profile:
    pattern: /profile
    defaults: { _controller: WGOpenIdUserBundle:Profile:index }
