parameters:
    cisco.ldap.client.class: CiscoSystems\LdapBundle\Ldap\Client
    cisco.ldap.directories: ~
    cisco.ldap.default_directory: ~

services:
    cisco.ldap:
        class: %cisco.ldap.client.class%
        arguments:
            - %cisco.ldap.directories%
            - %cisco.ldap.default_directory%
